# Travis continuous integration configuration file
matrix:
  include:
  - language: python
    python:
      - "2.7"
    install:
      - pip install -r requirements.txt
      - pip install python-coveralls
    script:
      - pytest --cov=mitxgraders --cov-report=term-missing
    after_success:
      - coveralls

  - language: node_js
    node_js:
      - "node"
    before_install:
      - "cd mitxgraders-js"
